# Generated by Django 5.0.14 on 2026-08-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR / Admin'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=25),
        ),
    ]
