# Generated by Django 5.0.14 on 2026-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('CEO', 'CEO'), ('HR', 'HR / Admin'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=25),
        ),
    ]
