# Generated by Django 5.2.17 on 2026-09-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('CEO', 'CEO'), ('HR', 'HR / Admin'), ('SUPERVISOR', 'Supervisor'), ('EMPLOYEE', 'Employee')], db_index=True, default='EMPLOYEE', max_length=25),
        ),
    ]
