# Generated by Django 5.0.14 on 2026-08-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LEAVE_SUBMITTED', 'Leave Request Submitted'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('WFH_SUBMITTED', 'WFH Request Submitted'), ('WFH_APPROVED', 'WFH Request Approved'), ('WFH_REJECTED', 'WFH Request Rejected'), ('CORRECTION_APPROVED', 'Attendance Correction Approved'), ('CORRECTION_REJECTED', 'Attendance Correction Rejected'), ('SALARY_INCREMENT', 'Salary Increment'), ('SALARY_DECREMENT', 'Salary Decrement'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
