# Generated by Django 5.0.14 on 2026-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_SUBMITTED', 'Leave Request Submitted'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('WFH_SUBMITTED', 'WFH Request Submitted'), ('WFH_APPROVED', 'WFH Request Approved'), ('WFH_REJECTED', 'WFH Request Rejected'), ('CORRECTION_SUBMITTED', 'Attendance Correction Submitted'), ('CORRECTION_APPROVED', 'Attendance Correction Approved'), ('CORRECTION_REJECTED', 'Attendance Correction Rejected'), ('SALARY_INCREMENT', 'Salary Increment'), ('SALARY_DECREMENT', 'Salary Decrement'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=30),
        ),
    ]
