# Generated by Django 5.2.17 on 2026-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAVE_SUBMITTED', 'Leave Request Submitted'), ('LEAVE_APPROVED', 'Leave Request Approved'), ('LEAVE_REJECTED', 'Leave Request Rejected'), ('WFH_SUBMITTED', 'WFH Request Submitted'), ('WFH_APPROVED', 'WFH Request Approved'), ('WFH_REJECTED', 'WFH Request Rejected'), ('CORRECTION_SUBMITTED', 'Attendance Correction Submitted'), ('CORRECTION_APPROVED', 'Attendance Correction Approved'), ('CORRECTION_REJECTED', 'Attendance Correction Rejected'), ('SALARY_INCREMENT', 'Salary Increment'), ('SALARY_DECREMENT', 'Salary Decrement'), ('PAYSLIP_RELEASED', 'Payslip Officially Released'), ('EARLYPASS_SUBMITTED', 'EarlyPass Request Submitted'), ('EARLYPASS_APPROVED', 'EarlyPass Request Approved'), ('EARLYPASS_REJECTED', 'EarlyPass Request Rejected'), ('EARLYPASS_CANCELLED', 'EarlyPass Request Cancelled'), ('LATE_CLOCK_IN_ALERT', 'Late Clock-in Alert'), ('LOCATION_UPDATE', 'Employee Location Update'), ('SYSTEM_ALERT', 'System Alert')], default='SYSTEM_ALERT', max_length=30),
        ),
    ]
