# Generated by Django 5.0.14 on 2026-08-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blockers',
            field=models.TextField(blank=True, help_text='Blockers or impediments encountered', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_tasks',
            field=models.TextField(blank=True, help_text='What the employee actually accomplished / did on this date', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_tasks',
            field=models.TextField(blank=True, help_text='What the employee is supposed / planned to do on this date', null=True),
        ),
    ]
