# Generated by Django 5.0.14 on 2026-08-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_shiftreport_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='face_verified',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='liveness_verified',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_method',
            field=models.CharField(choices=[('MANUAL_CORRECTION', 'Manual Correction'), ('WEB_PORTAL', 'Web Portal Clock')], default='WEB_PORTAL', max_length=20),
        ),
    ]
