# Generated by Django 5.0.14 on 2026-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_attendance_face_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('festival_type', models.CharField(choices=[('GENERAL', 'General Holiday'), ('OPTIONAL', 'Optional Festival Leave')], default='GENERAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
