# Generated by Django 5.2.17 on 2026-09-30 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancebreak'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Maintenance Worksite', max_length=150)),
                ('latitude', models.FloatField(default=17.385044, help_text='Target latitude set by CEO')),
                ('longitude', models.FloatField(default=78.486671, help_text='Target longitude set by CEO')),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='Allowed radius in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
