# Generated by Django 5.2.17 on 2026-09-30 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_maintenancegeofence'),
        ('employees', '0006_employee_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancegeofence',
            name='name',
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='resume_distance_meters',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='resume_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='resume_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancegeofence',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenancegeofence',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geofence_setting', to='employees.department'),
        ),
        migrations.AddField(
            model_name='maintenancegeofence',
            name='site_name',
            field=models.CharField(default='Maintenance Worksite', max_length=150),
        ),
        migrations.AlterField(
            model_name='maintenancegeofence',
            name='latitude',
            field=models.FloatField(default=17.385044),
        ),
        migrations.AlterField(
            model_name='maintenancegeofence',
            name='longitude',
            field=models.FloatField(default=78.486671),
        ),
        migrations.AlterField(
            model_name='maintenancegeofence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_geofences', to=settings.AUTH_USER_MODEL),
        ),
    ]
