# Generated by Django 5.2.17 on 2026-10-05 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_maintenancegeofence_name_and_more'),
        ('employees', '0007_employee_created_by_employee_is_maintenance_worker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyPassRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('request_date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('requested_exit_time', models.DateTimeField()),
                ('actual_exit_time', models.DateTimeField(blank=True, null=True)),
                ('required_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('actual_working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('missing_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('reason', models.TextField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='early_pass/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_early_passes', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_passes', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_pass_requests', to='employees.employee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_early_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EarlyPassAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
                ('new_status', models.CharField(max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_pass_audits', to=settings.AUTH_USER_MODEL)),
                ('early_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='attendance.earlypassrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
