# Generated by Django 5.0.14 on 2026-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='work_mode',
            field=models.CharField(choices=[('OFFICE', 'Office'), ('WFH', 'Work From Home'), ('HYBRID', 'Hybrid')], default='OFFICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='remaining_days',
            field=models.FloatField(default=12.0),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='number_of_days',
            field=models.FloatField(default=1.0),
        ),
    ]
