# Generated by Django 5.0.14 on 2026-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_half_day_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='allocated_days',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
