# Generated by Django 5.2.17 on 2026-10-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leavebalance_allocated_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, help_text='True if paid leave, False if Loss of Pay / Unpaid leave'),
        ),
    ]
