# Generated by Django 5.2.17 on 2026-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0005_seed_loss_of_pay_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='additional_leave_days',
            field=models.FloatField(default=0.0, help_text='Additional requested days beyond normal CL allowance'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='additional_leave_status',
            field=models.CharField(choices=[('NONE', 'Not Applicable'), ('PENDING', 'Pending Higher-Authority Approval'), ('APPROVED', 'Approved as Loss of Pay'), ('REJECTED', 'Rejected')], db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='cl_days',
            field=models.FloatField(default=0.0, help_text='Days covered under Casual Leave allowance'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='daily_salary_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily salary based on actual calendar days', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='expected_lop_deduction',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected or applied salary deduction for LOP days', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='lop_days',
            field=models.FloatField(default=0.0, help_text='Days approved as Loss of Pay'),
        ),
    ]
