# Generated by Django 5.0.14 on 2026-08-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
    ]
