# Generated by Django 5.0.14 on 2026-08-26 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_address_employee_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='biometric_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='face_profile_enrolled',
        ),
    ]
