# Generated by Django 5.0.14 on 2026-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_employee_biometric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leave_balance',
            field=models.FloatField(default=24.0),
        ),
    ]
