# Generated by Django 5.2.17 on 2026-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_mobile_access_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning Shift'), ('Evening', 'Evening Shift'), ('Night', 'Night Shift'), ('General', 'General Shift')], db_index=True, default='Morning', max_length=20),
        ),
    ]
