# Generated by Django 5.0.14 on 2026-08-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wfhrequest',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='wfhrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='half_day_period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='number_of_days',
            field=models.FloatField(default=1.0),
        ),
        migrations.RenameField(
            model_name='wfhrequest',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: __import__('django').apps.apps.get_model('wfh', 'WFHRequest').objects.update(end_date=__import__('django').db.models.F('start_date')),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
