# Generated by Django 5.0.14 on 2026-08-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfh', '0002_alter_wfhrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfhrequest',
            name='start_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
