# Generated by Django 5.2.17 on 2026-10-04 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_created_by_employee_is_maintenance_worker'),
        ('salaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayslipAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('present_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('optional_leave_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('casual_leave_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('other_paid_leave_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_paid_leave_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unpaid_absence_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actual_working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('expected_screen_time', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actual_screen_time', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('effective_payable_days', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('per_day_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_overrides', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjusted_payslips', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslip_adjustments', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
