# Generated by Django 5.2.17 on 2026-10-04 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_created_by_employee_is_maintenance_worker'),
        ('salaries', '0002_monthlypayslipadjustment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('VERIFIED', 'Verified'), ('RELEASED', 'Released'), ('REVOKED', 'Revoked')], db_index=True, default='GENERATED', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_day_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_calendar_days', models.PositiveSmallIntegerField(default=30)),
                ('company_working_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('present_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('casual_leave_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('optional_leave_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='employees.employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_payslips', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_payslips', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-created_at'],
                'unique_together': {('employee', 'year', 'month', 'version')},
            },
        ),
    ]
