# Generated by Django 5.0.14 on 2026-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='company_tagline',
            field=models.CharField(blank=True, default='Secure Enterprise Workspace Portal', max_length=200),
        ),
        migrations.AlterField(
            model_name='organizationsettings',
            name='company_name',
            field=models.CharField(default='FRG Enterprise', max_length=150),
        ),
    ]
