# Generated by Django 6.1 on 2026-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizationsettings_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='casual_leave_annual_entitlement',
            field=models.FloatField(default=12.0),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='optional_leave_annual_entitlement',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='salary_denominator_policy',
            field=models.CharField(choices=[('EFFECTIVE_WORKING_DAYS', 'Effective Working Days (Working Days - Paid Leaves)'), ('SCHEDULED_WORKING_DAYS', 'Scheduled Company Working Days'), ('CALENDAR_DAYS', 'Calendar Days'), ('FIXED_30', 'Fixed 30 Days'), ('FIXED_26', 'Fixed 26 Days')], default='EFFECTIVE_WORKING_DAYS', max_length=30),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='standard_daily_work_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=4),
        ),
    ]
