# Generated by Django 5.2.17 on 2026-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organizationsettings_casual_leave_annual_entitlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='company_address',
            field=models.TextField(blank=True, default='Plot No. 42, Hitech City, Hyderabad, Telangana - 500081'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='hr@frgenterprise.com', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+91 40 1234 5678', max_length=30),
        ),
    ]
