# Generated by Django 5.2.17 on 2026-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_organizationsettings_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_allow_cancellation',
            field=models.BooleanField(default=True, help_text='Whether employees can cancel pending requests'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_allow_same_day',
            field=models.BooleanField(default=True, help_text='Whether same-day EarlyPass requests are allowed'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_approval_role',
            field=models.CharField(choices=[('HR_OR_CEO', 'HR or CEO'), ('HR_ONLY', 'HR Only'), ('CEO_ONLY', 'CEO Only')], default='HR_OR_CEO', help_text='Which role(s) are authorized to approve EarlyPass', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_attachment_mandatory',
            field=models.BooleanField(default=False, help_text='Whether supporting attachment is mandatory'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_max_per_month',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed EarlyPass requests per month'),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_min_working_hours',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='Minimum hours worked before EarlyPass is allowed', max_digits=4),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='early_pass_require_advance',
            field=models.BooleanField(default=False, help_text='Whether advance submission prior to the date is required'),
        ),
    ]
